### PR TITLE
Update journal-sql.properties

### PR DESCRIPTION
**Pull request by franz1981**
It contains the changes that allow JDBC Shared Store Lease Locks and 
JDBC journal operation to be configured correctly

### CODE REVIEW

**Comment by mtaylor** [comment]
@jmesnil We need a single place for running EAP test suite against Artemis.  We are carrying a couple of changes in the messaging team right now, hence this PR.  Is this the best place to push things?  Cheers

**Comment by jmesnil** [comment]
@franz1981 @mtaylor that's definitely not the right place, I never updated the master branch on my local repo :)
Please use https://github.com/wildfly/wildfly/ for PR based on Artemis 1.5.x and https://github.com/jmesnil/wildfly/tree/WFLY-9407_upgrade_artemis_2.4.0_with_prefix for Artemis 2.x changes.

I had a quick glance (sorry, I'm on paternity leave and looked from my phone) and it seems some of these changes are already in WildFly upstream (latest related changes were from https://github.com/wildfly/wildfly/pull/11319.

Note that I have a pending PR to support HA JDBC store with Artemis 1.5.5.jbossorg-012 and I took the opportunity to switch to the Artemis property-based implementation: https://github.com/wildfly/wildfly/pull/11355

**Comment by franz1981** [comment]
Hi Jeff!
Answers inline

> Please use ...and https://github.com/jmesnil/wildfly/tree/WFLY-9407_upgrade_artemis_2.4.0_with_prefix for Artemis 2.x changes.

Do you mean another repo? because the one you have linked is exactly where I have sent this PR...

> it seems some of these changes are already in WildFly upstream

Let me take a look on it: essentialy we need this same branch (https://github.com/jmesnil/wildfly/tree/WFLY-9407_upgrade_artemis_2.4.0_with_prefix) + the sql changes I have sent through this PR: if we have it already, even better

> I'm on paternity leave

That's great!!! Congratulations!!!!!! :100:

**Comment by franz1981** [comment]
@jmesnil Jeff, probably I have missed some context: we are using this branch (WFLY-9407_upgrade_artemis_2.4.0_with_prefix) to perform tests vs the latest Artemis master so we need the changes on it; having them on wildfly master is good for EAP, but not to test 2.x.
That's why I have pushed the PR here: can you help me to have this branch updated so we can use it to perform tests?

**Comment by jmesnil** [comment]
@franz1981 I'm in paternity leave until the end of this week. I've merged your PR as is without reviewing it.

**Pull request merged**
